/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @vipin yadav labs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProductId = IDL.Nat;
export const Product = IDL.Record({
  'id' : ProductId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'specs' : IDL.Text,
  'imageUrl' : IDL.Text,
  'applications' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OrderId = IDL.Nat;
export const OrderStatus = IDL.Variant({
  'dispatched' : IDL.Null,
  'orderPlaced' : IDL.Null,
  'delivered' : IDL.Null,
  'processing' : IDL.Null,
});
export const Time = IDL.Int;
export const Order = IDL.Record({
  'id' : OrderId,
  'customerName' : IDL.Text,
  'status' : OrderStatus,
  'createdAt' : Time,
  'productName' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'notes' : IDL.Text,
  'quantity' : IDL.Nat,
  'phone' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_init' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProduct' : IDL.Func([Product], [ProductId], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrder' : IDL.Func([Order], [OrderId], []),
  'deleteProduct' : IDL.Func([ProductId], [], []),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getOrder' : IDL.Func([OrderId], [Order], ['query']),
  'getProduct' : IDL.Func([ProductId], [Product], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [], []),
  'updateProduct' : IDL.Func([Product], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProductId = IDL.Nat;
  const Product = IDL.Record({
    'id' : ProductId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'specs' : IDL.Text,
    'imageUrl' : IDL.Text,
    'applications' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OrderId = IDL.Nat;
  const OrderStatus = IDL.Variant({
    'dispatched' : IDL.Null,
    'orderPlaced' : IDL.Null,
    'delivered' : IDL.Null,
    'processing' : IDL.Null,
  });
  const Time = IDL.Int;
  const Order = IDL.Record({
    'id' : OrderId,
    'customerName' : IDL.Text,
    'status' : OrderStatus,
    'createdAt' : Time,
    'productName' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'notes' : IDL.Text,
    'quantity' : IDL.Nat,
    'phone' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_init' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProduct' : IDL.Func([Product], [ProductId], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrder' : IDL.Func([Order], [OrderId], []),
    'deleteProduct' : IDL.Func([ProductId], [], []),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getOrder' : IDL.Func([OrderId], [Order], ['query']),
    'getProduct' : IDL.Func([ProductId], [Product], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [], []),
    'updateProduct' : IDL.Func([Product], [], []),
  });
};

export const init = ({ IDL }) => { return []; };